### ISSUE TITLE
API Element Attributes "multipleDropdown" values not saving

### ISSUE THREAD

**Issue by DDfakt** [VisualComposer/builder#291] opened 2019-12-19 17:41 UTC
I tried to use the "multipleDropdown" attribute listed here:
https://visualcomposer.com/help/api/element-structure/

I configured it like a normal dropdown with a global variable.
The keys and values appear just fine in a multiple select. 
After selecting a few options and saving the page the multi-select is cleared again afterwards.

Are there any solutions or am I doing something wrong?

 - OS: macOS Catalina 10.15.1
 - Browser: Chrome
 - Version 78.0.3904.97 (Offizieller Build) (64-Bit)

**Comment by nikitahl** [comment] 2019-12-20 16:51
Sorry for the confusion. This attribute not working properly, that's why we've removed it from the API docs. You won't find it here: https://visualcomposer.com/help/api/element-attributes/#multipleDropdown
However, it's our bad that we didn't remove it from the list you're referring to, which adds the confusion.

We have a plan to fix it, so it can be used properly.

**Comment by nikitahl** [comment] 2020-01-02 13:53
The issue is fixed in the https://github.com/VisualComposer/builder/pull/301

**Comment by nikitahl** [comment] 2020-01-13 14:20
> The issue is fixed in the #301

**Closed by nikitahl** 2020-01-13 14:20 UTC
Labels: bug
